frontend/frontend/routes/auth.py
from flask import Blueprint, render_template, session, request, redirect, url_for

import re

# from ..modules.auth_func import logout_user



# Create the blueprint object
auth_bp = Blueprint(
    "auth_bp", __name__, template_folder="../templates", static_folder="../static"
)


# Main account page
@auth_bp.route("/")
def login():
    """Present users with options to login, or create account/logout if not logged in"""

    return render_template("auth_index_new.html.jinja2")


@auth_bp.route('/logout')
def logout():
    """Logout user"""
    return render_template("logout.html.jinja2")

    # # Went with JS solution instead
    # success = logout_user()
    #
    # return redirect(url_for('feed_bp.feed'))

frontend/frontend/routes/create.py
from flask import Blueprint, render_template, request, url_for, redirect, session
from datetime import datetime
import requests

from ..modules.api import BackendApi, ExternalApis
from ..modules.models import Post
from ..modules.auth_func import verify_auth

# Create the blueprint object
create_bp = Blueprint(
    "create_bp", __name__, template_folder="../templates", static_folder="static"
)

api = BackendApi()
ext_api = ExternalApis()


@create_bp.route("/", methods=["GET", "POST"])
def create_post():
    """Create a new post and upload it"""

    # check for authorization, redirect if not authorized
    check = verify_auth()

    if check is False:
        return redirect(url_for('auth_bp.login'))

    if request.method == "GET":
        return render_template('create_post.html.jinja2')

    else:
        # Get the form data
        post_data = request.form.to_dict()

        # Add a few attributes to post data
        post_data['user_id'] = session['user_id']
        post_data['timestamp'] = datetime.utcnow()
        post_data['tags'] = post_data['tags'].split()

        # Get user lat and lng
        lat, lng = ext_api.get_user_lat_lng(request)  # currently testing on localhost
        # lat, lng = ext_api.get_user_lat_lng('107.128.183.164')
        post_data['loc'] = [lng, lat]

        # Separate the filepath from the form data
        file = request.files['image_file'].read()

        # Create the post object
        post = Post(**post_data)

        # Send the data to the backend
        response = api.create_post(post, file)

        return redirect(url_for('feed_bp.feed'))

        #JSON decode error when try to do this
        #return redirect(url_for('view_bp.view_post', post_id=post_id))

        #return render_template(asdfasdf, post=post)

frontend/frontend/routes/delete.py
from flask import Blueprint, render_template, request, url_for, redirect, flash
from datetime import datetime
import requests

from ..modules.api import BackendApi, ExternalApis
from ..modules.models import Post

# Create the blueprint object
delete_bp = Blueprint(
    "delete_bp", __name__, template_folder="../templates", static_folder="static"
)

api = BackendApi()
ext_api = ExternalApis()


@delete_bp.route("/delete_post/<post_id>")
def delete_post(post_id):
    """Delete a post"""

    #needs auth
    """ (claims, error_message) = verify_auth(request.cookies.get('token'))

    if claims == None or error_message != None:
        return redirect(url_for('auth.login'))

    user = User().init_args(claims['name'], claims['email'])
    user.find_account() """

    #check to see if the user owns he post
    """ if user._id != post['owner'] and user.permission == 'user':
        error = 'You do not have permission to delete this post!'
        return render_template('error.html.jinja2', error=error)
 """
    #find the post by id
    post = api.delete_post(post_id=post_id)

    # flash("You have successfully deleted this post")
    return redirect(url_for('feed_bp.feed'))

frontend/frontend/routes/map.py
from flask import Blueprint, render_template, request, redirect, url_for
from ..modules.map import gmaps
from flask_googlemaps import Map, icons

from ..modules.api import BackendApi, ExternalApis
from ..modules.auth_func import verify_auth
from ..modules.filter import contruct_filters, breed_list

# Create the blueprint object
map_bp = Blueprint(
    "map_bp", __name__, template_folder="../templates", static_folder="static"
)

api = BackendApi()
ext_api = ExternalApis()

# Main account page
@map_bp.route("/", methods=["GET", "POST"])
def map():
    """Interactive map of dog spots in the area"""
    # check for authorization, redirect if not authorized
    check = verify_auth()

    if check is False:
        return redirect(url_for('auth_bp.login'))

    # Get user location
    user_lat, user_lng = ext_api.get_user_lat_lng(request)
    # user_lat, user_lng = ext_api.get_user_lat_lng(ip='107.128.183.164')

    filter_params = contruct_filters(request, user_lat, user_lng)

    print(filter_params)

    # Get posts with filter params (default or user-specified)
    posts = api.fetch_all_posts(filter_params)

    # Render the map
    icon = 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png'
    posts_markers = ([{
        'icon': icon,
        'lat': p['loc'][1],
        'lng': p['loc'][0],
        'infobox': f"<b>{p['title']}</b><br /><img src='{p['image_url']}' />"
    } for p in posts])

    gmap = Map(
        identifier="gmap",
        varname="gmap",
        lat=user_lat,
        lng=user_lng,
        markers=posts_markers,
    )


    # Make tags into string
    # try:
    #     filter_params['tags'] = " ".join(filter_params['tags'])
    # except KeyError:
    #     pass

    return render_template("map.html.jinja2", gmap=gmap, filters=filter_params, breeds=breed_list)

frontend/frontend/templates/auth_index.html.jinja2
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Firebase Login</title>

    <script src="https://www.gstatic.com/firebasejs/7.17.1/firebase-app.js"></script>

    <script src="https://www.gstatic.com/firebasejs/7.8.0/firebase-auth.js"></script>

    <script src="https://www.gstatic.com/firebasejs/7.17.1/firebase-analytics.js"></script>

    <!-- info to load the firebase login info -->
    <script src="https://cdn.firebase.com/libs/firebaseui/4.5.0/firebaseui.js"></script>
    <link type="text/css" rel="stylesheet" href="https://cdn.firebase.com/libs/firebaseui/4.5.0/firebaseui.css">

    <!-- load in the script for page functionality and the style css file
    not sure if this is the proper refernce place -->
    <script src="{{ url_for('.static', filename='auth_index.js') }}"></script>

    <!-- create css file for this-->
    <link type="text/css" rel="stylesheet" href="{{ url_for('.static', filename='style.css') }}">

    <script>
      // Your web app's Firebase configuration
      var firebaseConfig = {
        apiKey: "AIzaSyDpWEmVsPnE0KVFCN9mN7jgF7vSiewSvK0",
        authDomain: "team1-apad-project.firebaseapp.com",
        databaseURL: "https://team1-apad-project.firebaseio.com",
        projectId: "team1-apad-project",
        storageBucket: "team1-apad-project.appspot.com",
        messagingSenderId: "1091529426743",
        appId: "1:1091529426743:web:39a5a384b974bca8e6bcb2",
        measurementId: "G-5K8N9NWZB9"
      };
      // Initialize Firebase
      firebase.initializeApp(firebaseConfig);
      firebase.analytics();
    </script>

</head>
<body>
    <h1>hello, world!</h1>
    <!-- The core Firebase JS SDK is always required and must be listed first -->

    <div class="container">
      <div class="content-wrapper bg-white p-5 m-5 align-middle">
          <h1 class="py-5">PetZone</h1>
          <div id="firebaseui-auth-container"></div>
          <button id="sign-out" hidden=true>Sign out</button>

          <div id="login-info">
            <h2>Last login:</h2>
            {% if times %}
              <p>{{ times }} </p>
            {% elif error_message %}
              <p>Error: {{ error_message }}</p>
            {% endif %}
          </div>
    </div>



</body>
</html>

frontend/frontend/templates/auth_index_new.html.jinja2
<!--https://cloud.google.com/appengine/docs/standard/python/authenticating-users-firebase-appengine-->
<!doctype html>
<!--
Copyright 2016 Google Inc. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License");
-->
<html>
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <script src="https://www.gstatic.com/firebasejs/5.6.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/5.6.0/firebase-auth.js"></script>
  <script src="https://cdn.firebase.com/libs/firebaseui/3.4.1/firebaseui.js"></script>
  <link type="text/css" rel="stylesheet" href="https://cdn.firebase.com/libs/firebaseui/3.4.1/firebaseui.css">
  <link rel="stylesheet" type="text/css" href="{{ url_for('.static', filename='style_new.css') }}">
  <script src="{{ url_for('.static', filename='auth_index_new.js') }}"></script>
  <title>FYAP! - Login</title>
</head>
<body>
  <div id="logged-out">
    <h1>Find You a Pupper!</h1>
    <h3>Sign in to see some pups</h3>
    <div id="firebaseui-auth-container"></div>
  </div>
  <!-- need to add in this functionality
  <button id="sign-out">Sign out</button>
  -->
</body>
</html>

frontend/frontend/templates/base.html.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

    <!--stops favicon error
    <link rel="icon" href="data:;base64,iVBORw0KGgo=">
    -->
    <link rel="icon" href="{{ url_for('static', filename='favicon.png') }}">


    <!-- TRYING CAROUSEL-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <!----------------------------->

</head>
<body>
    <!-- BOOTSTRAP THEME FOR NAV BAR-->
    <!--Source: https://bootswatch.com/ (sandstone theme-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{{ url_for('feed_bp.feed') }}">Find You a Pupper!</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{{ url_for('feed_bp.feed') }}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('map_bp.map') }}">Map</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('create_bp.create_post') }}">Post a Dog Spot</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth_bp.logout') }}">Logout</a>
            </li>
          </ul>
          <!--
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
          </form>
          -->
        </div>
    </nav>
    <!------------------------------------------------------------------------------>

    <!--content-->
    <div class="center">
    {% block content %}
    {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
</html>

frontend/frontend/templates/create_post.html.jinja2
{% extends 'base.html.jinja2' %}

{% block title %}FYAP! - Create Post{% endblock %}

{% block content %}
<h1>Share That Pupper!</h1>

<form action="{{ url_for('.create_post') }}" method="post" enctype="multipart/form-data">
    <label for="image_file">Image</label><br />
    <input id="image_file" type="file" name="image_file"><br /><br />

    <label for="title">Title</label><br />
    <input id="title" type="text" name="title"><br /><br />

    <label for="breed_primary">Primary Breed</label><br />
    <input id="breed_primary" type="text" name="breed_primary"><br /><br />

    <label for="breed_secondary">Secondary Breed</label><br />
    <input id="breed_secondary" type="text" name="breed_secondary"><br /><br />

    <label for="tags">Tags (Separated By Spaces)</label><br />
    <input id="tags" type="text" name="tags"><br /><br />

    {# Hidden user ID #}
    <input id="uidInput" type="hidden" name="user_id"><br /><br />

    <input id="submit" type="submit" value="Submit Post"><br />
</form>

{# <script>
    var uid = firebase.auth().currentUser.uid;
    document.getElementById("uidInput").value = uid;
    console.log('set uid to ' + uid);
</script> #}

{% endblock %}

frontend/frontend/templates/delete_post.html.jinja2
{% extends 'base.html.jinja2' %}

{% block title %}FYAP! - Delete Post{% endblock %}

{% block content %}
<h1>Bye-bye, Puppo :(</h1>

<div id='post'>
    <div>
        <h4>"{{ post.title }}"</h4>
        <p>Breed: {{ post.breed_primary }}</p>
        <img src="{{ post.image_url }}" alt="{{ post.title }}" width="250px" height="150px">
        <br />
    </div>
    <input id="submit" type="submit" value="Delete Post"><br />

</div>


{% endblock %}

frontend/frontend/templates/error.html.jinja2
{% extends "base.html" %}
{% block content %}
    <!-- adapted from sample project -->
    <div class="container-fluid main-content">
        <div class="row">
            <div class="col-12 d-flex flex-column ">
                <h1>Oops, something went wrong.</h1>
                <p>{{error}}</p>
                <a href="javascript:history.back()">back</a>
              
            </div>
        </div>
{% endblock %}

frontend/frontend/templates/feed.html.jinja2
{% from "macros.html.jinja2" import post_display with context %}
{% extends "base.html.jinja2" %}

{% block title %}Find You a Pupper!{% endblock %}

{% block content %}
<h1>Welcome to Find You a Pupper!</h1>
<br />
<!-- carousel is adapted from https://www.w3schools.com/bootstrap/bootstrap_carousel.asp -->
<div class="container">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="/static/header1.png" alt="Comfy Boi" style="width:100%;">
      </div>

      <div class="item">
        <img src="/static/header2.png" alt="Silly Boi" style="width:100%;">
      </div>

      <div class="item">
        <img src="/static/header3.png" alt="Wet Boi" style="width:100%;">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<br />
<br />
<br />
<br />
<h2>Recently Spotted Doggos</h2><br />

<div class='card-columns'>
{% for post in posts %}
    {{ post_display(post, user_id) }}
    <br />
{% endfor %}
</div>
{% endblock %}

frontend/frontend/templates/filter.html.jinja2
{% macro filter(filters, breeds) %}

<form id="filter" class="filter-results" action="{{ url_for('map_bp.map') }}" method="post">

    <label for="breed_primary">Primary Breed</label>
    <select id="breed_primary" name="breed_primary">
        {% for breed in breeds %}
            {% if breed == filters['breed_primary'] %}
              <option value="{{ breed }}" selected>{{ breed }}</option>
            {% else %}
              <option value="{{ breed }}">{{ breed }}</option>
            {% endif %}
        {% endfor %}
    </select>

    <label for="breed_secondary">Secondary Breed</label>
    <select id="breed_secondary" name="breed_secondary">
        {% for breed in breeds %}
            {% if breed == filters['breed_secondary'] %}
              <option value="{{ breed }}" selected>{{ breed }}</option>
            {% else %}
              <option value="{{ breed }}">{{ breed }}</option>
            {% endif %}
        {% endfor %}
    </select>

    <label for="tags">Tags (separated by spaces)</label>
    <input id="tags" type="text" name="tags" value="{{ filters['tags'] }}">

    <label for="max_radius">Max Range (in miles)</label>
    <input id="max_radius" type="number" name="max_radius" value="{{ filters['max_radius'] }}"> |
    <!-- <button class="btn btn-warning" onClick="document.getElementById('filter').reset();">Reset</button><br /> -->
    <input type="reset" class="btn btn-warning"><br />

    <input class="btn btn-primary" id="submit" type="submit" value="Filter">


</form>
{% endmacro %}

frontend/frontend/templates/login.html.jinja2
{% extends 'base.html.jinja2' %}

{% block title %}Title{% endblock %}

{% block content %}
<h2>Login Page (under construction)</h2>

{% endblock %}

frontend/frontend/templates/logout.html.jinja2
{% block title %}Logout{% endblock %}

{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script src="https://www.gstatic.com/firebasejs/5.6.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/5.6.0/firebase-auth.js"></script>
<script src="https://cdn.firebase.com/libs/firebaseui/3.4.1/firebaseui.js"></script>
<link type="text/css" rel="stylesheet" href="https://cdn.firebase.com/libs/firebaseui/3.4.1/firebaseui.css">
<link rel="stylesheet" type="text/css" href="{{ url_for('.static', filename='style_new.css') }}">

<script>
  var config = {
    apiKey: "AIzaSyDpWEmVsPnE0KVFCN9mN7jgF7vSiewSvK0",
    authDomain: "team1-apad-project.firebaseapp.com",
    databaseURL: "https://team1-apad-project.firebaseio.com",
    projectId: "team1-apad-project",
    storageBucket: "team1-apad-project.appspot.com",
    messagingSenderId: "1091529426743",
    appId: "1:1091529426743:web:39a5a384b974bca8e6bcb2",
    measurementId: "G-5K8N9NWZB9"
  };

  if (!firebase.apps.length) {
    firebase.initializeApp(config);
  }

  firebase.auth().signOut().then(function() {
    // Delete all cookies
    console.log('success');
    document.cookie.split(";").forEach(function(c) { document.cookie = c.replace(/^ +/, "").replace(/=.*/, "=;expires=" + new Date().toUTCString() + ";path=/"); });
    console.log('cookies deleted')
    window.location.href = '../../';
  }, function(error) {
    console.log(error);
  });
</script>

{% endblock %}

frontend/frontend/templates/macros.html.jinja2
{% macro post_display(post, user_id) %}
<div class="card">
    <div class="card-img-top">
        <img src="{{ post.image_url }}" alt="{{ post.title }}">
    </div>
    <div class="card-body">
        <div class="card-title">
            <h4>"{{ post.title }}"</h4>
        </div>
        <br/>

        {% if post.breed_secondary|length > 0 %}
            <p>Breeds: {{ post.breed_primary }} / {{ post.breed_secondary }} Mix</p>
        {% else %}
            <p>Breed: {{ post.breed_primary }}</p>
        {% endif %}

        <small>Tags: {{ post.tags }}</small>
        <br />
        <br />

        <div class="links" style="white-space: nowrap;">
        <a href="{{ url_for('view_bp.view_post', post_id=post.id) }}">View Details</a>
        {% if user_id==post.user_id %}
            | <a href="{{ url_for('update_bp.update_post', post_id=post.id) }}">Edit</a> |
            <a href="{{ url_for('delete_bp.delete_post', post_id=post.id) }}">Delete</a>
        {% endif %}
        </div>
    </div>
</div>
{% endmacro %}

frontend/frontend/templates/map.html.jinja2
{% extends 'base.html.jinja2' %}

{% from 'filter.html.jinja2' import filter with context %}

{% block head %}{{ gmap.js }}{% endblock %}
{% block title %}FYAP! - Pupper Map{% endblock %}

{% block content %}

<h1>Cute Puppos Near You!</h1>
{{ filter(filters, breeds) }}
<hr />
<div class="map-div">
{{ gmap.html }}
</div>
{% endblock %}

frontend/frontend/templates/update_post.html.jinja2
{% extends 'base.html.jinja2' %}

{% block title %}FYAP! - Edit Post{% endblock %}

{% block content %}
<h1>Edit That Pupper!</h1>
<hr />

<form action="{{ url_for('.update_post', post_id=post.id) }}" method="post" enctype="multipart/form-data">
    {# <label for="image_file">Image</label><br /> #}
    <img src="{{ post.image_url }}" alt="{{ post.title }}" {# width="250px" height="150px" #}><br /><br />

    <label for="title">Title</label><br />
    <input value="{{ post.title }}" id="title" type="text" name="title"><br />

    <label for="breed_primary">Primary Breed</label><br />
    <input value="{{ post.breed_primary }}" id="breed_primary" type="text" name="breed_primary"><br />

    <label for="breed_secondary">Secondary Breed</label><br />
    <input value="{{ post.breed_secondary }}" id="breed_secondary" type="text" name="breed_secondary"><br />

    <label for="tags">Tags (Separated By Spaces)</label><br />
    <input value="{{ post.tags }}" id="tags" type="text" name="tags"><br />

    {# Hidden input fields #}
    <input value="{{ post.id }}" name="id" type="hidden">
    {# <input value="{{ post.user_id }}" name="user_id" type="hidden">
    <input value="{{ post.timestamp }}" name="timestamp" type="hidden">
    <input value="{{ post.loc }}" name="timestamp" type="hidden"> #}

    <input id="submit" type="submit" value="Save Changes"><br />

{% endblock %}

frontend/frontend/templates/view_post.html.jinja2
{% from 'macros.html.jinja2' import post_display with context %}
{% extends "base.html.jinja2" %}

{% block title %}Find You a Pupper!{% endblock %}

{% block content %}
<h1>View This Pupper</h1>

<div class="posts">
    {{ post_display(post, user_id) }}
    <br />
</div>
{% endblock %}